# frontend/Dockerfile
FROM node:18-alpine

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers et installer les dépendances
COPY package.json ./
RUN npm install

# Copier le code source
COPY . .

# Construire l'application React
RUN npm run build

# Utiliser un serveur nginx pour servir l'application
# FROM nginx:alpine
# COPY --from=0 /app/build /var/www/html

# Exposer le port 3000 pour le frontend
EXPOSE 5000

# Commande de démarrage
CMD ["npm", "run", "dev"]