version: "3.9"

services:
  # Service Backend
  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "127.0.0.1:${BACKEND_PORT}:8000"
    depends_on:
      - redis
    networks:
      - app-network

  # Service Frontend
  frontend:
    build:
      context: ./frontend
    env_file:
      - ./frontend/.env
    ports:
      - "127.0.0.1:${FRONTEND_PORT}:80"
    depends_on:
      - backend
    networks:
      - app-network

  # Service Redis
  redis:
    image: redis:latest
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge