version: "3.9"

# Service Backend
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - redis
    networks:
      - app-network

  # Service Frontend
  frontend:
    build:
      context: ./frontend
    ports:
      - "5000:5000"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    networks:
      - app-network

  # Service Redis
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
