# backend/Dockerfile
FROM node:18

# Répertoire de travail
WORKDIR /src/app

# Copier les fichiers et installer les dépendances
COPY package.json ./
RUN npm install

# Copier le code source
COPY . .
RUN npm run build

# Exposer le port pour le backend
EXPOSE 8000

# Commande de démarrage
CMD [ "npm", "run", "start" ]